---

- name: Installing Dependencies
  yum:
    name:
      - python3
      - python3-pip

- name: Docker file
  yum:
    name: docker
    update_cache: yes
  register: docker

- name: Docker
  pip:
    name: docker
    state: latest
  when: docker.change
  
- name: Create Docker group
  group:
    name: docker
    state: present

- name: Add Docker Group to User
  user:
    name: mgascuevas-tip
    group: docker
