- name: Install prerequisites
  yum:
    pkg:
      - mariadb
      - mariadb-server
      - python2-PyMySQL
   
- name: create openstack.cnf
  file:
    path: /etc/my.cnf.d/openstack.cnf
    state: touch
    
- name: enable mariadb
  service:
    name: mariadb
    state: started
    enabled: yes
     
