
- name: create db keystone
  community.mysql.mysql_db:
    name: keystone
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock

      #- name: give proper access or grant
      # mysql_user:
      #name: root
      #password: ''
      #priv:
      #'keystone.*': 'ALL,GRANT'
      

- name: install o-keystone
  yum:
    name: openstack-keystone
    state: latest

- name: install httpd
  yum:
    name: httpd
    state: latest

- name: install mod_wsgi
  yum:
    name: mod_wsgi
    
- name: Insert connection to database
  blockinfile:
    path: /etc/keystone/keystone.conf
    insertafter: "[database]"
    block: |
      # ...
      connection = mysql+pymysql://keystone:ged156435@controller/keystone
      
- name: Insert connection to token
  blockinfile:
    path: /etc/keystone/keystone.conf
    insertafter: "[token]"
    block: |
      # ...
      provider = fernet
        
- name: populate identity service
  command:  su -s /bin/sh -c "keystone-manage db_sync" keystone
    
- name: Initialize Fernet key repositories
  command: keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone

- name: fernet two
  command: keystone-manage credential_setup --keystone-user keystone --keystone-group keystone
      
- name: bootstrap identity service
  command: keystone-manage bootstrap --bootstrap-password ADMIN_PASS --bootstrap-admin-url http://controller:5000/v3/ --bootstrap-internal-url http://controller:5000/v3/ --bootstrap-public-url http://controller:5000/v3/ --bootstrap-region-id RegionOne

- name: edit server name of port
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '# ServerName gives the name and port that the server uses to identify itself'
    line: ServerName controller
    
- name: start httpd service
  service:
    name: httpd
    state: started
    enabled: yes

      #- name: configure admin account
      #command: export OS_USERNAME=gedrei

- name: conf2
  command: export OS_PASSWORD=ged156435

- name: conf3
  command: export OS_PROJECT_NAME=mgascuevas-tip

- name: conf4
  command: export OS_USER_DOMAIN_NAME=Default

- name: conf5
  command: export OS_PROJECT_DOMAIN_NAME=Default

- name: conf6
  command: export OS_AUTH_URL=http://controller:5000/v3

- name: conf last
  command: export OS_IDENTITY_API_VERSION=3
      
 

    
    
 
