- name: Installing prereq
  yum:
    name:
      - httpd
      - gcc
      - glibc
      - glibc-common
      - gd-devel
      - perl
      - postfix
      - unzip
    state: latest
    update_cache: yes

- name: HTTPD start
  service:
    name: httpd
    state: started

- name: Nagios group
  group:
    name: nagios
    state: present

- name: create Nagios group
  group:
    name: nagcmd
    state: present

- name: create nagios User
  user:
    name: nagios
    shell: /bin/bash
    comment: nagios user
    group: nagios
    password: ged156435

- name: put httpd to nagios group
  user:
    name: apache
    groups: nagios
    append: yes

- name: nagios user ext cmd
  user:
    name: nagios
    group: nagcmd
    append: yes

- name: www-data user 
  user:
    name: www-data
    group: nagcmd
    append: yes

- name: downloads folder
  file: 
    path: /downloads
    state: directory

- name: download nagios
  get_url:
    url: http://prdownloads.sourceforge.net/sourceforge/nagios/nagios-4.2.1.tar.gz
    dest: /downloads

- name: nagios core unarchive
  unarchive:
    src: /downloads/nagios-4.2.1.tar.gz
    dest: /downloads
    remote_src: yes

- name: vh directory
  file:
    path: /etc/httpd/conf.d
    state: directory

- name: nagios conf
  shell: ./configure --with-command-group=nagcm --with-command-group=nagcmd --with-httpd_conf=/etc/httpd/conf.d
  args:
    chdir: /downloads/nagios-4.2.1

- name: compile nagios
  make:
    chdir: /downloads/nagios-4.2.1
    target: all

- name: install
  make:
    chdir: /downloads/nagios-4.2.1
    target: install

- name: init script install
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-daemoninit

- name: config files installation
  make: 
    chdir: /downloads/nagios-4.2.1
    target: install-config

- name: permissions
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-commandmode

- name: nagios interface
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-webconf

- name: classic UI theme
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-classicui

- name: Pip installation for htpasswd
  yum:
    name: python3-pip
    state: latest
    update_cache: yes

- name: htpasswd module installation
  pip:
    name: passlib
    state: latest

- name: nagiosadmin account
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: gedrei
    password: ged156435

- name: apache restart
  service:
    name: httpd
    state: reloaded

- name: nagios service enable ans start
  shell: '/usr/local/nagios/bin/nagios -d /usr/local/nagios/etc/nagios.cfg'
