prelim_exam: https://github.com/mgascuevas-tip/sysad2-2022.git
username: mgascuevas-tip
writable_chroot: allow_writeable_chroot=YES
ftp_config: "allow_writeable_chroot=YES\npasv_min_port=30000\npasv_max_port=31000\nuserlist_file=/etc/vsftpd/user_list\nuserlist_deny=NO"
ftp:debian: "pasv_enable=Yes\npasv_min_port=10000\npasv_max_port=10100\nallow_writeable_chroot=YES\nssl_tlvs1=YES\nssl_sslv2=NO\nssl_sslv3=NO"
ftp_user: gedrei
ftp_pass: ged156435
naguser_pass: ged156435
nagadmin_pass: ged156435
