---

- name: Installing Dependencies
  apt:
    name:
      - python3
      - python3-pip
    update_cache: yes

- name: Docker file
  apt:
    name: docker.io
    update_cache: yes
  register: docker

- name: Docker.py
  pip:
    name: docker.py
  when: docker.changed
  
- name: Run Docker Service
  service:
    name: docker
    state: started
    enabled: yes

- name: Initialize Docker to install Web Server
  docker_image:
    name: newdeveloper/apache-php
    state: present
    source: pull

- name: Utilizing Docker to Install db server
  docker_image:
    name: mysql/mysql-server:latest
    state: present
    source: pull

- name: Create Docker Group
  group:
    name: docker
    state: present

- name: Add Docker Group to User
  user:
    name: mgascuevas-tip
    group: docker
